-
  name: Install Softwares
  hosts: droplet
  vars:
    packages: 
      - name: nginx
        required: true
      - name: mysql
        required: true
      - name: apache
        required: false
  tasks:
    - name: Install {{ item.name }} on Debian
      apt:
        name: "{{ item.name }}"
        state: present
      when: item.required == true
      loop: "{{ packages }}"